CREATE TABLE RESIDENT_INFO (
    RESIDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    HOME_ADDRESS VARCHAR(100),  
    FULL_NAME VARCHAR(100) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GENDER ENUM('Male', 'Female', 'Other') NOT NULL,
    CIVIL_STATUS ENUM('Single', 'Married', 'Widowed', 'Annuled') NOT NULL,
    CONTACT_DETAILS VARCHAR(15),
    HOUSEHOLD_DETAILS TEXT,
    OCCUPATION VARCHAR(100),
    EMPLOYER_DETAILS VARCHAR(100),
    EDUCATIONAL_BACKGROUND TEXT,
    BARANGAY_INVOLVEMENT TEXT,
    MEDICAL_CONDITIONS TEXT,
    EMERGENCY_CONTACTS TEXT,
    BLOOD_TYPE ENUM('A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'),
    LENGTH_OF_STAY INT,  
    PREVIOUS_RESIDENCE VARCHAR(100),
    PROOF_OF_RESIDENCY VARCHAR(100),
    BUSINESS_PERMIT_NUMBER VARCHAR(100),
    BUSINESS_PERMIT_ISSUED_BY VARCHAR(100) 
);

CREATE TABLE EMPLOYEE_INFO (
    EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
    FULL_NAME VARCHAR(100) NOT NULL,
    POSITION VARCHAR(100) NOT NULL,
    CONTACT_DETAILS VARCHAR(15), 
    ROLE_RESPONSIBILITIES TEXT,  
    OFFICE_HOURS VARCHAR(100),  
    OFFICE_LOCATION VARCHAR(100),  
);
